# Generated by Django 4.2.23 on 2025-07-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Email topic/subject', max_length=200)),
                ('to_email', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('app_password', models.CharField(help_text='Gmail app password', max_length=100)),
                ('doc_text', models.TextField(blank=True, help_text='Document content for AI analysis')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('attachment_files', models.JSONField(default=list, help_text='List of attachment file paths')),
                ('scheduled_time', models.DateTimeField(help_text='When to send the email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('generated_subject', models.CharField(blank=True, max_length=200)),
                ('generated_body', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scheduled Email',
                'verbose_name_plural': 'Scheduled Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.scheduledemail')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
            },
        ),
    ]
